#
# SPDX-FileCopyrightText: Copyright (c) Siemens AG 2019-2026 ALL RIGHTS RESERVED
# SPDX-License-Identifier: MIT
#

name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gradle:9.2.1-jdk17
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: 'add-jdk8'
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: 8
                  set-default: false

            - name: versions
              run: |
                  echo JAVA_HOME=${JAVA_HOME}
                  echo PATH=${PATH}
                  git --version
                  echo '---'
                  java -version
                  echo '---'
                  ${JAVA_HOME_8_X64}/bin/java -version
                  echo '---'
                  export EXTRA_JDKS="-Dorg.gradle.java.installations.paths=${JAVA_HOME_8_X64}"
                  echo "EXTRA_JDKS=${EXTRA_JDKS}" >> "$GITHUB_ENV"
                  gradle ${EXTRA_JDKS} javaToolchains

            - name: build
              run: |
                  gradle ${EXTRA_JDKS} --warning-mode all clean build

            - name: codecov
              uses: codecov/codecov-action@v6
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
